name: SSH Debugging
on: [push]
jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Connection
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -vvv -i ssh_key ec2-user@${{ secrets.EC2_HOST }}