name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ## Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Hostname
        run: |
          echo "Hostname: ${{ secrets.EC2_HOST }}"
      
      - name: Verify key
        run: |
          echo "Using private key: ${{ secrets.EC2_SSH_KEY }}"

      # Step 2: Deploy to EC2 via SSH using the private key stored in GitHub Secrets
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5 # Updated version for stability
        with:
          host: ${{ secrets.EC2_HOST }}       # The public IP address or DNS name of your EC2 instance
          username: ec2-user                   # Default username for Amazon Linux AMI
          key: ${{ secrets.EC2_SSH_KEY }}      # Reference the secret containing your private SSH key
          port: 22                             # Default SSH port
          script: |
            cd ~
            /deploy.sh
          debug: true 
