name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ## Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Hostname
        run: |
          echo "Hostname: ${{ secrets.EC2_HOST }}"
      
      - name: Verify key
        run: |
          echo "Using private key: ${{ secrets.EC2_SSH_KEY }}"

      # Step 2: Deploy to EC2 via SSH using the private key stored in GitHub Secrets
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5 # Updated version for stability
        with:
          host: ${{ secrets.EC2_HOST }}       # The public IP address or DNS name of your EC2 instance
          username: ec2-user                   # Default username for Amazon Linux AMI
          key: ${{ secrets.EC2_SSH_KEY }}      # Reference the secret containing your private SSH key
          port: 22                             # Default SSH port
          script: |
            # Navigate to the directory containing the project
            cd ~/UMOD
            
            # Pull the latest changes from the GitHub repository
            git fetch origin main
            git reset --hard origin/main

            # Make deploy.sh executable
            chmod +x deploy.sh

            # Execute the deployment script
            ./deploy.sh

            docker stop your_app_container || true
            docker rm your_app_container || true

            # Remove old Docker image
            docker rmi your_app_image || true

            # Build the new Docker image
            docker build -t your_app_image .

            # Run the container using the new image
            docker run -d -p 8000:8000 --name your_app_container your_app_image

            echo "Deployment completed!"
          debug: true
