name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
              # Use the latest version of actions/checkout (which is compatible with Node.js 16)
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home
            ./deploy.sh
